package qoder

import (
	"encoding/hex"
	"testing"
)

// Reference vectors generated by testdata_gen.js against the 9router JS
// implementation. These lock byte-for-byte parity for the deterministic
// primitives (AES-CBC, MD5 sig input, WAF encoding). The full COSY header set
// cannot be pinned because AES key, timestamp, and UUIDs are random per request.

func TestAESEncryptCBCBase64_Parity(t *testing.T) {
	const (
		plaintext = `{"uid":"user-123","security_oauth_token":"dt-abc","name":"","aid":"","email":""}`
		key       = "1234567890abcdef"
		wantB64   = "bkUDv/dd6kbYoADFcJYPN4bhFYSt7eZ4R4GKPIbmOrwJqQirH0bxCaT7GrYTks4FjXPWulIri7N4PESpBI5+4sWOQTKGVHor9fTQEnyeKDxMLu0jX/+S7VP4XlqRuv2v"
	)
	got, err := aesEncryptCBCBase64(plaintext, key)
	if err != nil {
		t.Fatalf("aesEncryptCBCBase64: %v", err)
	}
	if got != wantB64 {
		t.Fatalf("AES parity mismatch:\n got=%s\nwant=%s", got, wantB64)
	}
}

func TestMD5SigInput_Parity(t *testing.T) {
	// sigInput = payloadB64 \n cosyKey \n timestamp \n body \n sigPath
	sigInput := "payloadB64\ncosyKeyValue\n1700000000\n{\"a\":1}\n/api/v2/x"
	const want = "ae2e9f0a64ecea699938b7606914f7a8"
	if got := md5Hex([]byte(sigInput)); got != want {
		t.Fatalf("MD5 parity mismatch: got=%s want=%s", got, want)
	}
}

func TestQoderEncodeBody_Parity(t *testing.T) {
	in := `{"request_id":"abc","stream":true,"messages":[{"role":"user","content":"hello world"}]}`
	const wantHex = "422a476f4b4d7528517744535177424d6e2a50484672754871264a2857597548702a65462e5729774e45464c476f4b7444786a5e23534a4c4e594279536b722a4e4f5772442c42794245465e44786d594b594478672e44786a7778284c7a424d6e2a23534b4d422a662a4e6b435944536774424d"
	got := qoderEncodeBody([]byte(in))
	if gotHex := hex.EncodeToString(got); gotHex != wantHex {
		t.Fatalf("encode parity mismatch:\n got=%s\nwant=%s", gotHex, wantHex)
	}
}

func TestComputeSigPath(t *testing.T) {
	cases := map[string]string{
		"https://api3.qoder.sh/algo/api/v2/x?y=1": "/api/v2/x",
		"https://api3.qoder.sh/api/v2/x":          "/api/v2/x",
		"":                                        "",
	}
	for in, want := range cases {
		if got := computeSigPath(in); got != want {
			t.Errorf("computeSigPath(%q)=%q want %q", in, got, want)
		}
	}
}

func TestPKCS7Pad(t *testing.T) {
	// 5 bytes -> pad to 16 with 11 bytes of 0x0b.
	got := pkcs7Pad([]byte("hello"), 16)
	if len(got) != 16 {
		t.Fatalf("len=%d want 16", len(got))
	}
	for i := 5; i < 16; i++ {
		if got[i] != 11 {
			t.Fatalf("pad byte %d = %d want 11", i, got[i])
		}
	}
	// Exact multiple -> full extra block.
	got = pkcs7Pad(make([]byte, 16), 16)
	if len(got) != 32 {
		t.Fatalf("len=%d want 32", len(got))
	}
}

func TestBuildCosyHeaders_Shape(t *testing.T) {
	body := []byte(`{"a":1}`)
	url := "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation?x=1"
	h, err := buildCosyHeaders(body, url, cosyCreds{UserID: "u1", AuthToken: "dt-tok", MachineID: "mach-1"})
	if err != nil {
		t.Fatalf("buildCosyHeaders: %v", err)
	}
	required := []string{
		"Authorization", "Cosy-Key", "Cosy-User", "Cosy-Date", "Cosy-Version",
		"Cosy-Machineid", "Cosy-Machinetoken", "Cosy-Machinetype", "Cosy-Machineos",
		"Cosy-Clienttype", "Cosy-Clientip", "Cosy-Bodyhash", "Cosy-Bodylength",
		"Cosy-Sigpath", "Cosy-Data-Policy", "Login-Version", "X-Request-Id",
	}
	for _, k := range required {
		if h[k] == "" && k != "Cosy-Organization-Id" {
			t.Errorf("missing header %q", k)
		}
	}
	if h["Cosy-User"] != "u1" {
		t.Errorf("Cosy-User=%q", h["Cosy-User"])
	}
	if h["Cosy-Machineid"] != "mach-1" || h["Cosy-Machinetoken"] != "mach-1" {
		t.Errorf("machine id mismatch: %q / %q", h["Cosy-Machineid"], h["Cosy-Machinetoken"])
	}
	if h["Cosy-Sigpath"] != "/api/v2/service/pro/sse/agent_chat_generation" {
		t.Errorf("Cosy-Sigpath=%q", h["Cosy-Sigpath"])
	}
	if h["Cosy-Bodylength"] != "7" {
		t.Errorf("Cosy-Bodylength=%q want 7", h["Cosy-Bodylength"])
	}
	if h["Authorization"][:12] != "Bearer COSY." {
		t.Errorf("Authorization prefix=%q", h["Authorization"][:12])
	}
	// Empty creds must error.
	if _, err := buildCosyHeaders(body, url, cosyCreds{AuthToken: "x"}); err == nil {
		t.Error("expected error for empty user id")
	}
	if _, err := buildCosyHeaders(body, url, cosyCreds{UserID: "x"}); err == nil {
		t.Error("expected error for empty auth token")
	}
}
