package frontend

import (
	"embed"
	"io/fs"
)

// DistFS contains the embedded production assets generated by Vite build.
//
//go:embed all:dist
var DistFS embed.FS

// FS returns an fs.FS sub-rooted at "dist".
func FS() fs.FS {
	sub, err := fs.Sub(DistFS, "dist")
	if err != nil {
		return DistFS
	}
	return sub
}
